background color nav action added breadcrumb
BCTCio/components pull request #42
Opened 2022-11-25 21:42 UTC by alexusernamebruh

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/85073684/204057604-88f4133a-019b-4fe9-8f58-6efa36318fff.png">
Light theme
-
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/85073684/204057632-67068815-625d-45f6-bbd9-2f720775eb8b.png">
Dark theme
-
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/85073684/204057721-8804dca7-6db4-41bf-a091-0c54a1398ad9.png">
I couldn't find how to change the light and dark theme from this icon(I googled for like 30 minutes and found nothing on how to do it) so I created an control instead
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/85073684/204057778-b3109b9e-cc21-4274-975d-37f05e2cf00f.png">

2022-11-30 21:11 UTC, ssysm commented
single quote please

2022-11-30 21:11 UTC, ssysm requested changes

2022-11-30 21:11 UTC, ssysm commented on src/components/Breadcrumbs/index.stories.tsx
> +  title: "Elements/Breadcrumbs",
single

2022-12-03 19:42 UTC, RichardX366 requested changes

2022-12-03 19:42 UTC, RichardX366 commented on src/components/Breadcrumbs/index.stories.tsx
> +      title: "Title",
still has double quotes

2022-12-03 19:42 UTC, RichardX366 commented on src/components/Breadcrumbs/index.tsx
> +  backgroundColor = background,
backgroundColor = 'light'

2022-12-03 19:42 UTC, RichardX366 commented on src/components/Breadcrumbs/index.tsx
> +let background = 'light';
remove

2022-12-03 19:42 UTC, RichardX366 commented on src/components/Breadcrumbs/index.tsx
> +const DarkMode =
do the dark mode background handling inside the stories file by just adding another ComponentStory

2022-12-03 19:42 UTC, RichardX366 commented on src/components/Breadcrumbs/index.tsx
> +  backgroundColor?: 'light' | 'dark';
darkMode?: boolean

2022-12-03 19:42 UTC, RichardX366 commented on src/components/Breadcrumbs/index.tsx
> +  if (backgroundColor === 'light') {
instead of doing this if statement, just do ternary for the classnames checking for darkMode

2023-04-15 06:41 UTC, mxdi9i7 commented
Where is the code that actually adds the background?

2023-04-18 00:06 UTC, closed without merging