add dark mode breadcrumbs
BCTCio/components pull request #45
Opened 2022-12-08 00:09 UTC by alexusernamebruh

2022-12-08 05:08 UTC, RichardX366 requested changes
Can you do the `darkMode: 'class'` inside the tailwind config thing? https://tailwindcss.com/docs/dark-mode

2022-12-08 05:08 UTC, RichardX366 commented on src/components/Breadcrumbs/index.tsx
> +    <nav className='flex ' aria-label='Breadcrumb'>
remove the space

2022-12-08 05:08 UTC, RichardX366 commented
Also attach screenshot of dark and not dark

2022-12-08 12:52 UTC, alexusernamebruh commented
Kk, will do tonight

2022-12-09 02:23 UTC, mxdi9i7 commented
can we also add a prop to the component that allows dark to be set manually by the user?

2022-12-09 02:23 UTC, mxdi9i7 commented
a prop called `dark` that is a boolean

2022-12-09 22:17 UTC, alexusernamebruh commented
yes sir

2022-12-10 21:57 UTC, RichardX366 requested changes

2022-12-10 21:57 UTC, RichardX366 commented on src/components/Breadcrumbs/index.tsx
> +  if (darkMode === true) {
dont change the whole component just modify the classes

2022-12-10 21:57 UTC, RichardX366 commented on src/components/Breadcrumbs/index.stories.tsx
> +    'bg-gray-900 px-2 py-2 border border-gray-300 hover:border-gray-600 rounded-lg ';
remove ending space

2022-12-10 21:57 UTC, RichardX366 commented on src/components/Breadcrumbs/index.stories.tsx
> +if (props.darkMode === false) {
use else ifs.
put in order
props.darkMode
props.darkMode === false
else

2023-01-23 16:42 UTC, merged