Pagination place holder can now be inputted number to go to that page
BCTCio/components pull request #52
Opened 2023-02-04 22:23 UTC by alexusernamebruh

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/85073684/216791958-0a765c49-8b56-4b43-b027-1b79200f72c1.png">

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/85073684/216791971-9ff54972-9013-42a6-ae74-95476a317be4.png">

2023-02-08 18:24 UTC, mxdi9i7 commented on src/components/Pagination/index.tsx
> +                  //auto sizing
could you reposition comments to top of the code it's commenting?

2023-02-28 22:18 UTC, ssysm requested changes

2023-02-28 22:18 UTC, ssysm commented on src/components/Pagination/index.tsx
> +  const [text1, setText1] = useState<number | string>('...');
meaningful variable

2023-03-07 01:45 UTC, mxdi9i7 approved these changes

2023-03-08 22:11 UTC, merged