add
BCTCio/components pull request #55
Opened 2023-02-24 00:30 UTC by alexusernamebruh

add custom no options selected place holder, default to 'No options selected'
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/85073684/221062321-ea93f0ac-4ca0-4970-a883-ecb3d40c91f9.png">

2023-02-28 22:18 UTC, ssysm requested changes

2023-02-28 22:18 UTC, ssysm commented on src/components/MultiSearchInput/index.tsx
> +              displayValue={(v) =>
strongly infer, `v`. If `v` is null have a proper handling case.

2023-03-02 01:00 UTC, mxdi9i7 commented on src/components/MultiSearchInput/index.tsx
> +interface displayValue {
this interface is not called displayvalue, it's actually the DropdownData, also you wouldn't include `length` in its interface

2023-03-07 01:45 UTC, mxdi9i7 commented on src/components/MultiSearchInput/index.tsx
> +                  v?.length
dropdown data doesn't have a length property. it's not an array

2023-03-07 01:45 UTC, mxdi9i7 requested changes
pls fix

2023-04-18 00:05 UTC, closed without merging